### ISSUE TITLE
Compiler setting

### ISSUE THREAD

**Issue by JamesMolson** [Merlin-Collaboration/Nightly-build-scripts#1]
Would it not make more sense to have this in the local.cmake file?
Say you want to switch to icc or clang, you currently need to modify every single file.

(do you have the systemd scripts too?) 🗡

**Comment by Sam-Tygier** [comment]
I was thinking that the default compiler settings for the whole project should be changed. The debug should be "-Og" on every compiler that supports it, and probably "-O3 -march=native" on the release builds.

I can add the systemd files to this repo if you think its useful.

**Comment by Sam-Tygier** [comment]
My previous answer misunderstood the issue. So I think 69a0cb2daac5152eb64f0280968e21038754955f fixes it. The default compiler is now set in Merlin.cmake. Putting

`set(CMAKE_CXX_COMPILER "clang")`

in your local.cmake, would override it for all the scripts. And setting it in an individual script (e.g. MerlinNightlyReleaseCDash.cmake ) would override it for that script.
